<<<<<<< HEAD
server:
  port: 9095
=======

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/clientes_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update


>>>>>>> faae6775c36d7e1e6ef0557bdc66d791650015be
